# Rust CI Pipeline
name: rust-ci
on:
  push:
    paths:
      - "**.rs"
      - "**.toml"
      - ".github/workflows/*.yml"
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10
  CARGO_TERM_COLOR: always

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rust-src

    - name: Format
      id: format
      run: cargo fmt -- --check

    - name: Run clippy
      id: clippy
      run: cargo clippy --verbose -- -D warnings

    - name: build
      id: build
      run: cargo build --release

    - name: Run tests
      id: tests
      run: cargo test --verbose
